/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SimpleEvote_CONSTANTS_H
#define SimpleEvote_CONSTANTS_H

#include "SimpleEvote_types.h"



class SimpleEvoteConstants {
 public:
  SimpleEvoteConstants();

};

extern const SimpleEvoteConstants g_SimpleEvote_constants;



#endif
